export const cityCountryMap: Record<string, string> = {
  // US Cities
  'kansas-city': 'us',
  'philadelphia': 'us',
  'arlington': 'us',
  'dallas': 'us',
  'las-vegas': 'us',
  'miami': 'us',
  'lincoln': 'us',
  'houston': 'us',
  'chicago': 'us',
  'orlando': 'us',
  'nyc': 'us',
  'austin': 'us',
  'san-diego': 'us',
  'phoenix': 'us',
  'atlanta': 'us',
  'charlotte': 'us',
  'los-angeles': 'us',
  'nashville': 'us',
  'denver': 'us',
  'fort-worth': 'us',
  'indianapolis': 'us',
  'portland': 'us',
  'oklahoma': 'us',
  'sacramento': 'us',
  'san-francisco': 'us',
  'colorado-springs': 'us',
  'salt-lake-city': 'us',
  'san-antonio': 'us',
  'wichita': 'us',
  'st-louis': 'us',
  'evansville': 'us',
  'cincinnati': 'us',
  'cleveland': 'us',
  'columbus': 'us',
  'charleston': 'us',
  'shreveport': 'us',
  'buffalo': 'us',
  'albany': 'us',
  'gaithersburg': 'us',
  'virginia-beach': 'us',
  'springfield': 'us',
  'lexington': 'us',
  'fayetteville': 'us',
  'providence': 'us',
  'little-rock': 'us',
  'milwaukee': 'us',
  'fort-lauderdale': 'us',
  'raleigh': 'us',

  // UK Cities
  'london': 'uk',
  'manchester-uk': 'uk',
  'birmingham': 'uk',
  'edinburgh': 'uk',
  'liverpool': 'uk',
  'leeds-uk': 'uk',
  'sheffield': 'uk',
  'glasgow': 'uk',
  'nottingham': 'uk',
  'bournemouth': 'uk',
  'bristol': 'uk',
  'oxford': 'uk',
  'york': 'uk',
  'leicester': 'uk',


  // Australian Cities
  'sydney': 'au',
  'melbourne': 'au',
  'brisbane': 'au',
  'perth': 'au',
  'adelaide': 'au',
  'gold-coast': 'au',
  'newcastle': 'au',
  'canberra': 'au',
  'wollongong': 'au',
  'sunshine-coast': 'au',

  // New Zealand Cities
  'auckland': 'nz',
  'wellington': 'nz',
  'christchurch': 'nz',
  'dunedin': 'nz'
};
